import json,os
DIR='data/curated';T='2026-07-27'
G=['menunjukkan betapa beragamnya kondisi geografis','menyimpan cerita menarik tentang bagaimana geografi','dapat fokus pada niche ekonomi spesialis','ketergantungan pada impor','Sebagai negara mikro','rentan terhadap badai tropis/siklon','menjadi modal pembangunan berkelanjutan','Memiliki akses ke laut/samudra memberikan','Ukuran compact','garis pantai yang sepenuhnya dikelola','peluang perdagangan maritim, perikanan, dan pelabuhan','negara kepulauan/pulau','menghadapi tantangan RUANG HIDUP','(meski jenisnya berbeda-beda)']
def hg(t):return any(p in t for p in G)

D={
"MH":{"keuntungan_geografis":["Kepulauan Marshall 1.225 pulau karang tersebar 2 juta km persegi Pasifik — ZEE sangat luas.","Atol Kwajalein salah satu atol terbesar dunia — fasilitas uji coba rudal AS.","Perairan kaya ikan tuna dan kelapa sebagai komoditas utama."],"kerugian_geografis":["Atol rata-rata 2 m di atas laut — kenaikan permukaan laut ancaman eksistensial.","Terpencil di Pasifik — bergantung bantuan AS dan impor total."],"fakta_unik":["Atol Bikini tempat uji coba nuklir AS 1946-1958 — crater nuklir masih radioaktif.","Kepulauan Marshall memiliki laguna terbesar dunia — Kwajalein 2.174 km persegi.","Waktu lokal Marshall +12 UTC — salah satu tempat paling pertama menyambut tahun baru."]},
"MK":{"keuntungan_geografis":["Makedonia Utara di Balkan dikelilingi pegunungan — posisi crossroads Eropa Selatan.","Danau Ohrid (288 m terdalam Balkan) salah satu danau tertua Eropa — UNESCO.","Lembah Vardar koridor alami antara Aegea dan Eropa Tengah."],"kerugian_geografis":["Tidak punya akses laut — terkurung darat oleh Yunani, Bulgaria, Serbia, Albania.","Wilayah bergunung menyulitkan pertanian dan transportasi."],"fakta_unik":["Danau Ohrid berusia 3-5 juta tahun — habitat 200+ spesies endemik.","Matka Canyon di dekat Skopje gua-gua bawah tanah dengan danau tersembunyi.","Makedonia Utara satu-satunya negara yang merdeka dari Yugoslavia tanpa perang."]},
"ML":{"keuntungan_geografis":["Mali terletak di Afrika Barat, berbatasan 7 negara — titik transit Sahara-Sahel.","Sungai Niger mengalir 1.700 km di Mali — menyediakan irigasi dan transportasi vital.","Delta Interior Niger di tengah Mali — satu dari beberapa delta sungai pedalaman dunia."],"kerugian_geografis":["65% wilayah gurun Sahara — utara sangat kering dan tidak bisa dihuni.","Terkurung darat — salah satu negara paling jauh dari laut di Afrika."],"fakta_unik":["Bandiagara Escarpment tebing 500 m — tempat tinggal Dogon selama 700 tahun.","Sungai Niger membentuk lengkungan besar ke utara lalu kembali ke selatan — fenomena unik.","Tombouctou (Timbuktu) di tepi Sahara kota emas abad ke-15 — pusat perdagangan garam."]},
"MO":{"keuntungan_geografis":["Makau di delta Sungai Mutiara 60 km dari Hong Kong — posisi strategis perdagangan China.","Pelabuhan Makau salah satu tersibuk di dunia — jembatan Hong Kong-Zhuhai-Makau 55 km.","Status SAR memberikan otonomi ekonomi — casino terbesar di dunia melampaui Las Vegas."],"kerugian_geografis":["Sangat kecil (32,9 km persegi) dan padat — seluruh negara lebih kecil dari satu kota.","Tidak punya sumber air tawar — bergantung pada China daratan."],"fakta_unik":["Makau menghasilkan 5x pendapatan casino Las Vegas — GDP per kapita tertinggi di Asia.","Jembatan Hong Kong-Zhuhai-Makau 55 km jembatan laut terpanjang di dunia.","Makau adalah COLONI EROPA pertama dan terakhir di China (1557-1999)."]},
"MT":{"keuntungan_geografis":["Malta di tengah Mediterania — posisi strategis antara Eropa, Afrika Utara, dan Timur Dekat.","Pelabuhan Grand Harbour Valletta salah satu pelabuhan alami terbaik Mediterania.","Iklim Mediterania dan 300 hari cerah — destinasi wisata dan film (Gladiator, Troy)."],"kerugian_geografis":["Sangat kecil (316 km persegi) padat (1.500/km persegi) — salah satu terpadat di dunia.","Tidak punya sumber air tawar atau sumber daya alam — bergantung impor dan desalinasi."],"fakta_unik":["Malta punya MEGALIT tertua di dunia — tempat Ggantija 3.600 SM, lebih tua dari Piramida.","Valletta ibu kota terkecil di EU — seluruh kota Situs Warisan Dunia UNESCO.","Blue Grotto Malta gua laut dengan cahaya biru spektakuler — salah satu spot diving terbaik."]},
"MU":{"keuntungan_geografis":["Mauritius di Samudra Hindia 2.000 km lepas pantai Afrika — posisi strategis jalur perdagangan Asia-Afrika.","Terumbu karang sekitar 300 km persegi mengelilingi pulau — surga diving kelas dunia.","Iklim tropis sepanjang tahun dan pantai berpasir putih — destinasi wisata premium."],"kerugian_geografis":["Pulau vulkanik kecil (2.040 km persegi) terisolasi — biaya logistik tinggi.","Sumber daya alam terbatas — bergantung impor dan sektor jasa."],"fakta_unik":["Dodo burung endemik Mauritius punah 1681 — simbol punahnya spesies.","Mauritius SATU-SATUNYA negara Afrika yang tidak berbatasan daratan dengan negara Afrika lain.","Golfs Tamarin dan Chamarel pasir 7 warna — formasi pasir vulkanik unik di dunia."]},
"MV":{"keuntungan_geografis":["Maladewa 1.192 pulau karang di Samudra Hindia — atol terbanyak di dunia.","Perairan jernih dan terumbu karang spektakuler — destinasi diving terbaik dunia.","Posisi di khatulistiwa memberikan iklim tropis stabil sepanjang tahun."],"kerugian_geografis":["Titik tertinggi hanya 2,4 m — negara TERENDAH di dunia, sangat rentan kenaikan laut.","Pulau kecil dengan sumber daya nol — air tawar, makanan, energi semuanya impor."],"fakta_unik":["Maladewa negara TERENDAH di dunia — rata-rata 1,5 m di atas laut.","Male ibu kota terpadat di dunia — 200.000 orang di 8,5 km persegi.","Atol Vaadhoo fenomena bioluminescence — laut bercahaya biru di malam hari."]},
"MZ":{"keuntungan_geografis":["Mozambik garis pantai 2.470 km terpanjang di Afrika timur — akses langsung Samudra Hindia.","Selat Mozambik antara Afrika dan Madagaskar — jalur pelayaran penting Samudra Hindia.","Sungai Zambezi membentuk delta luas di utara — potensi irigasi dan energi hidro."],"kerugian_geografis":["Sungai Zambezi banjir besar berkala — menghancurkan desa dan pertanian.","Infrastruktur minim akibat perang saudara 15 tahun — jalan dan jembatan banyak rusak."],"fakta_unik":["Pulau Mozambiq (Ilha de Mocambique) jembatan batu 3,8 km — Situs Warisan Dunia.","Taman Nasional Gorongosa salah satu yang paling beragam di Afrika.","Mozambiq punya pantai Tofo terkenal dengan hiu paus dan manta ray."]},
"NA":{"keuntungan_geografis":["Namibia garis pantai 1.570 km di Atlantik selatan — Gurun Namib bertemu laut langsung.","Gurun Namib tertua di dunia (55 juta tahun) — lanskap unik Sossusvlei dan Deadvlei.","Diamond area terpencil di selatan — Namibia produsen berlian berkualitas tinggi."],"kerugian_geografis":["Gurun Namib dan Kalahari menutupi 92% wilayah — salah satu paling kering di Afrika.","Terkurung darat dari segi ekonomi — pelabuhan hanya Walvis Bay dan Luderitz."],"fakta_unik":["Sossusvlei dune 325 m — salah satu gurun pasir tertinggi di dunia berwarna oranye kemerahan.","Deadvlei pohon mati 900 tahun berdiri di gurun putih — lanskap paling ikonik Afrika.","Skeleton Coast ribuan bangkai kapal dan paus di pantai — disebut Pesisir Tengkorak."]},
"NC":{"keuntungan_geografis":["Kaledonia Baru di Pasifik selatan dengan laguna terbesar dunia (24.000 km persegi).","Terumbu karang 1.600 km mengelilingi pulau — Situs Warisan Dunia UNESCO.","Cadangan nikel terbesar ke-5 dunia — 25% cadangan nikel global."],"kerugian_geografis":["Terpencil di Pasifik — 1.200 km dari Australia, biaya transportasi tinggi.","Bergantung pada Prancis untuk bantuan ekonomi dan keamanan."],"fakta_unik":["Laguna Kaledonia Baru 24.000 km persegi terbesar di dunia — UNESCO.","Terumbu karang 1.600 km rumah 9.000+ spesies laut — keanekaragaman laut tertinggi Pasifik.","Kagu burung endemik Kaledonia Baru — tidak bisa terbang, salah satu burung paling langka."]},
"NE":{"keuntungan_geografis":["Niger di Sahel Afrika barat — berbatasan 7 negara posisi transit Sahara.","Sungai Niger mengalir di ujung barat daya — menyediakan irigasi untuk pertanian.","Cadangan uranium terbesar di Afrika — Niger pengekspor uranium ke-4 dunia."],"kerugian_geografis":["80% wilayah gurun Sahara — utara sangat kering tidak bisa dihuni.","Terkurung darat, salah satu negara paling miskin di dunia."],"fakta_unik":["Air Terjun Tanimaka oasis di tengah gurun Sahara — salah satu keajaiban alam Niger.","Niger punya W National Park berbagi dengan Benin dan Burkina Faso — habitat gajah singa.","Agadez kota oasis di jalur Sahara — menara masjidnya ikonik dari tanah bake."]},
"PG":{"keuntungan_geografis":["Papua Nugini pulau terbesar di Pasifik (462.840 km persegi) setelah Greenland.","Hutan hujan tropis paling luas di Pasifik — keanekaragaman hayati luar biasa.","Laut Bismarck dan Salomon kaya sumber daya alam — minyak, gas, dan mineral."],"kerugian_geografis":["Medan pegunungan sangat terjal — hanya 2% daratan cocok pertanian.","Terpencil dari pasar utama — biaya transportasi sangat tinggi."],"fakta_unik":["Papua Nugini punya 850+ bahasa — 12% bahasa dunia ada di satu negara.","Puncak Wilhelm (4.509 m) gunung tertinggi Oceania di luar Australia.","Pulau New Britain punya gunung berapi Tavurvur — letusan 1994 menghancurkan Rabaul."]},
"PH":{"keuntungan_geografis":["Filipina 7.641 pulau di Asia Tenggara — garis pantai 36.289 km terpanjang ke-5 dunia.","Terletak di Cincin Api Pasifik — tanah vulkanik sangat subur untuk pertanian.","Laut Sulu dan Sulawesi kaya keanekaragaman hayati laut — Center of Marine Biodiversity."],"kerugian_geografis":["Di jalur typhoon Pasifik — rata-rata 20 typhoon per tahun, paling banyak di dunia.","Kepulauan terpencil membuat kesenjangan ekonomi — Mindanao tertinggal dari Luzon."],"fakta_unik":["Filipina punya gunung berapi paling aktif di dunia — Mayon (2.462 m) letusan 50x sejak 1616.","Taal Volcano pulau dalam danau dalam pulau — kompleks vulkanik paling unik di dunia.","Chocolate Hills di Bohol 1.268 bukit kerucut — UNESCO Global Geopark."]},
"RS":{"keuntungan_geografis":["Serbia di persimpangan Eropa Tengah dan Selatan — posisi koridor antara Laut Hitam dan Mediterania.","Sungai Danube dan Sava bertemu di Beograd — sungai terpenting Eropa.","Dataran Pannonia di utara menyediakan lahan pertanian paling subur di Balkan."],"kerugian_geografis":["Tidak punya akses laut — terkurung darat setelah Montenegro merdeka.","Pegunungan menyulitkan koneksi dengan tetangga."],"fakta_unik":["Beograd salah satu ibu kota tertua di Eropa — berdiri sejak 279 SM.","Uvac Canyon meander sungai berbentuk angka 8 — salah satu formasi sungai unik di Eropa.","Djurdevic Tara Bridge 365 m di atas ngarai — salah satu jembatan paling spektakuler di Balkan."]},
"RW":{"keuntungan_geografis":["Rwanda dataran tinggi 1.000-4.500 m di Afrika timur — iklim sedang sepanjang tahun.","Danau Kivu di perbatasan dengan Kongo — danau terdalam ke-15 di dunia.","Tanah vulkanik sangat subur di pegunungan — Rwanda pengekspor teh dan kopi berkualitas."],"kerugian_geografis":["Terkurung darat dan terpadat di Afrika (525/km persegi) — tekanan lahan masif.","Topografi berbukit menyebabkan erosi tanah parah."],"fakta_unik":["Rwanda disebut Negara Seribu Bukit — hamparan bukit hijau tanpa akhir.","Gunung Berapi Karisimbi (4.507 m) habitat gorila gunung — salah satu primata paling langka.","Rwanda adalah negara paling bersih di Afrika — plastik sekali pakai dilarang sejak 2008."]},
"SB":{"keuntungan_geografis":["Kepulauan Solomon 992 pulau di Pasifik selatan — keanekaragaman laut spektakuler.","Terumbu karang sekitar kepulauan terbesar di Pasifik selatan setelah GBR.","Hutan hujan menutupi 77% pulau — keanekaragaman hayati tinggi."],"kerugian_geografis":["Terpencil dan minim infrastruktur — banyak pulau tidak memiliki listrik.","Aktif secara seismik dan vulkanik — gempa dan tsunami mengancam."],"fakta_unik":["Guadalcanal tempat Pertempuran Guadalcanal Perang Dunia II — bangkai kapal masih ada.","Kepulauan Solomon punya laguna Marovo terbesar di dunia berdinding ganda.","Rennell Island danau Tegano laguna dalam pulau — Situs Warisan Dunia UNESCO."]},
"SC":{"keuntungan_geografis":["Seychelles 115 pulau karang dan granit di Samudra Hindia — destinasi wisata premium.","Pantai Anse Source d'Argent berpasir granit merah muda — salah satu pantai terindah dunia.","Perairan kaya tuna dan ikan — perikanan sumber pendapatan utama."],"kerugian_geografis":["Pulau kecil terpencil 1.600 km dari Afrika — biaya transportasi sangat tinggi.","Sumber daya alam sangat terbatas — bergantung impor dan pariwisata."],"fakta_unik":["Seychelles punya Aldabra Atoll — atol terbesar yang dihuni kura-kura raksasa.","Pulau Praslin habitat coco de mer — kelapa terbesar di dunia berbobot 25 kg.","Seychelles negara terkecil di Afrika (459 km persegi) — hanya 100.000 penduduk."]},
"SG":{"keuntungan_geografis":["Singapura di ujung Selat Malaka — posisi strategis jalur pelayaran tersibuk di dunia.","Pelabuhan Singapura tersibuk ke-2 di dunia — 37 juta TEU kontainer per tahun.","Posisi di khatulistiwa memberikan iklim tropis stabil sepanjang tahun."],"kerugian_geografis":["Sangat kecil (733 km persegi) tanpa sumber daya alam — air, makanan, energi semuanya impor.","Terbatasnya lahan menyebabkan harga properti tertinggi di dunia."],"fakta_unik":["Singapura mereklamasi 25% lahannya dari laut — Marina Bay dan Gardens by the Bay di atas tanah reklamasi.","Changi Airport consistently terbaik di dunia — terminal jewel terminal terindah.","Pulau Sentosa dibangun dari reklamasi — Universal Studios dan resort mewah di atas laut."]},
"SL":{"keuntungan_geografis":["Sierra Leone di pesisir Afrika Barat 402 km garis pantai — Pelabuhan Freetown alami.","Hutan tropis menyimpan keanekaragaman hayati tinggi — habitat simpai dan chimpanzee.","Sungai Rokel dan penyu di pantai — potensi ekowisata yang belum dimanfaatkan."],"kerugian_geografis":["Perang saudara 1991-2002 menghancurkan infrastruktur — jalan dan jembatan banyak rusak.","Sawah dan perkebunan terbengkalai saat konflik — pemulihan pertanian sangat lambat."],"fakta_unik":["Freetown didirikan sebagai koloni untuk budak yang dibebaskan — Mountain Village pertama.","Pulau Banana terkenal saat erupsi 1780 — Thomas Paine menulis tentangnya.","Sierra Leone punya pantai Tokeh salah satu terindah Afrika Barat."]},
"SM":{"keuntungan_geografis":["San Marino di puncak Pegunungan Apennine Italia — posisi strategis antara Rimini dan Romawi.","Tanah berbukit indah dengan iklim Mediterania — destinasi wisata sejarah.","Posisi di jantung Italia memberikan akses ekonomi ke pasar Eropa terbesar."],"kerugian_geografis":["Negara terkecil di Eropa (61 km persegi) — seluruh negara lebih kecil dari Jakarta Selatan.","Terkurung total oleh Italia — ekonomi sangat bergantung pada Italia."],"fakta_unik":["San Marino republik tertua di dunia yang masih bertahan — berdiri sejak 301 M.","Gunung Titano (749 m) tiga puncak di tengah negara — Situs Warisan Dunia UNESCO.","San Marino menerbitkan stamp unik — filateli menjadi sumber pendapatan penting."]},
"SN":{"keuntungan_geografis":["Senegal di ujung barat Afrika — Tanjung Almadies titik paling barat daratan Afrika.","Garis pantai 531 km di Atlantik — Dakar pelabuhan utama Afrika Barat.","Sungai Senegal (1.700 km) perbatasan alami dengan Mauritania — sumber irigasi."],"kerugian_geografis":["Sahel di utara semakin gurun — desertifikasi mengancam pertanian.","Sahara menggusur wilayah subur ke selatan secara perlahan."],"fakta_unik":["Tanjung Almadies titik paling barat Afrika daratan — monumen ini ikonik Dakar.","Ile de Goree pulau budak di lepas Dakar — Situs Warisan Dunia mengenang perdagangan budak.","Lac Rose (Retba) danau berwarna PINK di luar Dakar — warna dari organisme halofil."]},
"SR":{"keuntungan_geografis":["Suriname di pesisir utara Amerika Selatan — 386 km garis pantai di Atlantik.","Hutan hujan menutupi 93% wilayah — proporsi hutan tertinggi di dunia.","Sungai-surinya mengalir ke Atlantik — potensi energi hidro besar."],"kerugian_geografis":["Hutan lebat menyulitkan transportasi dan pembangunan infrastruktur.","Pesisir banyak rawa-rawa — akses ke pedalaman sangat sulit."],"fakta_unik":["Suriname negara terkecil di Amerika Selatan (163.820 km persegi).","Central Suriname Nature Reserve Situs Warisan Dunia — 1,6 juta hektar hutan primer.","Suriname satu-satunya negara Belanda Selatan — bahasa resminya Belanda."]},
"SS":{"keuntungan_geografis":["Sudan Selatan di Afrika timur-tengah — Sungai Nil Putih mengalir utara-selatan.","Sudd Swamp salah satu rawa terbesar dunia (57.000 km persegi) di Sungai Nil.","Tanah savana dan hutan di selatan subur — potensi pertanian besar."],"kerugian_geografis":["Tidak punya akses laut — terkurung darat, infrastruktur nyaris nol.","Banjir Sungai Nil menghancurkan desa dan pertanian tiap musim hujan."],"fakta_unik":["Sudd Swamp rawa terbesar dunia — 57.000 km persegi mengalir lambat di Nil Putih.","Sudan Selatan negara termuda di dunia — merdeka 2011 dari Sudan.","Migrasi antelope tiang-uang kedua terbesar di Afrika — 1,2 juta ekor di Taman Nasional Boma."]},
"ST":{"keuntungan_geografis":["Sao Tome dan Principe di Teluk Guinea — kepulauan vulkanik dengan tanah sangat subur.","Puncak Pico de Sao Tome (2.024 m) ciptakan iklim mikro — kaki gunung panas, puncak dingin.","Perairan kaya ikan dan terumbu karang — potensi ekowisata bahari."],"kerugian_geografis":["Kepulauan kecil (1.001 km persegi) terpencil di Teluk Guinea.","Sumber daya alam terbatas — bergantung bantuan internasional."],"fakta_unik":["Sao Tome salah satu tempat terkecil di dunia yang bisa lihat kedua sisi samudra dari puncak.","Kakao Sao Tome salah satu yang termahal — varietas tertua yang dibawa Portugis 1820.","Taman Nasional Obo menutupi 30% pulau — habitat 700+ spesies tumbuhan dan 100+ burung."]},
"SX":{"keuntungan_geografis":["Sint Maarten bagian selatan (Belanda) dari pulau Saint Martin — pelabuhan cruise terbesar Karibia.","Teluk Great Bay pelabuhan alami — kapal pesiar bisa berlabuh langsung di pantai.","Posisi di Lesser Antilles menarik turis dari AS dan Eropa."],"kerugian_geografis":["Pulau kecil (34 km persegi) sumber air dan lahan terbatas.","Badai Karibia merusak secara berkala — Hurricane Irma 2017 penghancuran besar."],"fakta_unik":["Sint Maarten pelabuhan cruise terbesar Karibia — menerima 2 juta turis per tahun.","Pulau Saint Martin terkecil dibagi dua negara — 34 km persegi untuk dua bangsa.","Princess Juliana Airport salah satu paling dramatis — pesawat terbang rendah di atas pantai."]},
"TD":{"keuntungan_geografis":["Chad di tengah Afrika — Danau Chad perbatasan 4 negara sumber air vital.","Sahara utara dan savana selatan — keberagaman ekosistem dalam satu negara.","Cadangan minyak di selatan (Doba Basin) mengubah ekonomi sejak 2003."],"kerugian_geografis":["Terkurung darat dan sangat jauh dari laut — negara paling terisolasi di Afrika.","Danau Chad menyusut 90% sejak 1960 — mengancam kehidupan 30 juta orang."],"fakta_unik":["Danau Chad dulunya danau ke-6 terbesar Afrika — sekarang hampir menghilang.","Tibesti Mountains di utara Sahara puncak Emi Koussi (3.445 m) tertinggi Sahara.","Chad nama berasal dari danau — danau itu sendiri dari bahasa Kanuri meaning air."]},
"TL":{"keuntungan_geografis":["Timor-Leste di ujung tenggara Asia — posisi dekat Australia dan jalur pelayaran Indonesia.","Pegunungan Ramelau (2.986 m) dan laut Sawu kaya minyak dan gas.","Terumbu karang Atauro dan pantai belum terjamah — potensi wisata bahari besar."],"kerugian_geografis":["Infrastruktur hancur akibat pendudukan Indonesia dan kemerdekaan — pembangunan dari nol.","Bergantung bantuan internasional — salah satu negara termuda dan termiskin di Asia."],"fakta_unik":["Timor-Leste merdeka 2002 — negara pertama yang merdeka di abad ke-21.","Pulau Atauro punya biodiversitas laut tertinggi di dunia menurut rekam CNS.","Timor-Leste menghasilkan kopi organik terbesar — kopi disebut kopi Timor Hybrido."]},
"TO":{"keuntungan_geografis":["Tonga 170 pulau di Pasifik selatan — satu-satunya negara di Pasifik yang tidak pernah dijajah.","Pesisir terumbu karang melindungi laguna alami — habitat paus bungkuk dan lumba-lumba.","Tanah vulkanik subur — Tonga mengekspor labu dan vanila."],"kerugian_geografis":["Kepulauan terpencil di Pasifik — biaya transportasi dan logistik sangat tinggi.","Pulau rendah rentan kenaikan laut dan tsunami."],"fakta_unik":["Tonga SATU-SATUNYA negara Pasifik yang tidak pernah dijajah — kerajaan 1.000+ tahun.","Ha'amonga 'a Maui triliton batu raksasa — Stonehenge Pasifik dari 1200 M.","Tonga 2015 letusan gunung bawah laut Hunga Tonga menciptakan pulau baru dalam 1 bulan."]},
"TT":{"keuntungan_geografis":["Trinidad dan Tobago di lepas pantai Venezuela — dekat ladang minyak lepas pantai.","Cadangan minyak dan gas alam besar — Trinidad produsen gas alam terbesar Karibia.","Puncak El Cerro del Aripo (940 m) dan hutan hujan di utara Trinidad — keanekaragaman tinggi."],"kerugian_geografis":["Hanya 2 pulau kecil (5.130 km persegi) — ekonomi terlalu bergantung minyak.","Posisi dekat Venezuela membuat rentan terhadap masalah keamanan regional."],"fakta_unik":["Pitch Lake di Trinidad danau aspal terbesar alami di dunia — 40 hektar aspal cair.","Trinidad punya Caroni Bird Sanctuary habitat scarlet ibis — burung merah ikonik.","Tobago coral reef berdekatan pantai — snorkeling langsung dari bibir pantai."]},
"VC":{"keuntungan_geografis":["Saint Vincent dan Grenadines 32 pulau di Karibia selatan — posisi dekat Barbados.","Gunung Soufriere (1.234 m) tanah vulkanik subur — pertanian dan ekowisata.","Terumbu karang Grenadines surga diving — Turks and Caicos of the south."],"kerugian_geografis":["Pulau-pulau kecil dan terpencil — infrastruktur dan sumber daya terbatas.","Gunung berapi Soufriere AKTIF — letusan April 2021 evakuasi 20.000 orang."],"fakta_unik":["Gunung Soufriere letusan April 2021 — kubah lava tumbuh di danau kawah.","Bequia island tradisi pembangunan perahu — salah satu dari sedikit di Karibia.","Botanical Garden Saint Vincent tertua di Hemisfer Barat — didirikan 1765."]},
"VU":{"keuntungan_geografis":["Vanuatu 83 pulau di Pasifik selatan — posisi di Ring of Fire.","Gunung Yasur (361 m) gunung berapi paling mudah diakses di dunia — wisatawan bisa naik ke kawah.","Perairan kaya ikan dan terumbu karang — surga diving kelas dunia."],"kerugian_geografis":["Pulau-pulau gunung berapi aktif — gempa bumi dan tsunami sering terjadi.","Terpencil di Pasifik — biaya transportasi dan logistik sangat tinggi."],"fakta_unik":["Vanuatu tempat BUNGEE JUMPING pertama — tradisi naghol (land diving) dari tiang kayu.","Tanna island kultus cargo Prince Philip — suku Yaohnanen menyembah Pangeran Philip.","Vanuatu HAPPINESS INDEX tertinggi di dunia menurut Happy Planet Index."]},
"WS":{"keuntungan_geografis":["Samoa 10 pulau di Pasifik selatan — posisi strategis jalur pelayaran trans-Pasifik.","Pulau Savaii gunung berapi aktif dengan hutan hujan tropis — keanekaragaman hayati tinggi.","Perairan kaya ikan — perikanan dan pariwisata sumber pendapatan utama."],"kerugian_geografis":["Terpencil di Pasifik — biaya transportasi dan logistik tinggi.","Siklon tropis menghantam berkala — Cyclone Evan 2012 kerusakan besar."],"fakta_unik":["Samoa tempat Robert Louis Stevenson tinggal — makamnya di puncak bukit Vailima.","Samoa pertama di dunia melihat matahari terbit tiap hari — tepat di east of date line.","Pulau Savaii meletus 1905-1911 — sebagian pulau tertutup lava hitam."]},
"YE":{"keuntungan_geografis":["Yaman menguasai selat Bab el-Mandeb — jalur minyak tersibuk ke-2 setelah Hormuz.","Pulau Sokotra (620 km dari daratan) keanekaragaman hayati luar biasa — 700+ spesies endemik.","Pegunungan barat (Jabal an Nabi Shuayb 3.666 m) tertinggi Semenanjung Arab."],"kerugian_geografis":["70% wilayah gurun dan semi-gurun — air sangat terbatas, salah satu paling kering di dunia.","Perang saudara menghancurkan infrastruktur — pelabuhan dan jalan rusak parah."],"fakta_unik":["Sokotra 700+ spesies endemik — pohon darah Dracaena cinnabari hanya ada di sini.","Kota Sanaa ibu kota tertinggi di dunia (2.300 m) — bangunan bergaya unik.","Selat Bab el-Mandeb hanya 29 km lebar — 6% perdagangan dunia melewatinya."]},
"ZM":{"keuntungan_geografis":["Zambia berbagi Victoria Falls dengan Zimbabwe — air terjun terbesar di dunia.","Sungai Zambezi membentuk perbatasan selatan — potensi energi hidro dan ekowisata.","Dataran tinggi (1.000-1.500 m) iklim sedang — ideal pertanian dan peternakan."],"kerugian_geografis":["Terkurung darat setelah pemisahan dari Rhodesia — bergantung negara tetangga.","Musim kering panjang menyebabkan kekeringan berkala di selatan."],"fakta_unik":["Victoria Falls (Mosi-oa-Tunya) air terjun terbesar di dunia — 1,7 km lebar 108 m tinggi.","Zambia berbagi Danau Kariba terbesar buatan di dunia — dengan Zimbabwe.","Walking Safari lahir di Zambia — satu-satunya tempat safari berjalan kaki di Afrika."]},
"ZW":{"keuntungan_geografis":["Zimbabwe berbagi Victoria Falls — air terjun terbesar di dunia, sumber utama turis.","Dataran tinggi (1.000-2.000 m) iklim sedang — Zimbabwe dulu disebut pantry Afrika.","Danau Kariba danau buatan terbesar di dunia — energi hidro dan perikanan."],"kerugian_geografis":["Terkurung darat — akses laut melalui Mozambik dan Afrika Selatan.","Hiperinflasi dan krisis ekonomi menyebabkan kolaps infrastruktur."],"fakta_unik":["Victoria Falls dari sisi Zimbabwe lebih spektakuler — 70% air terjun terlihat dari sini.","Great Zimbabwe reruntuhan kota batu terbesar di Afrika selatan — nama negara berasal dari sini.","Danau Kariba 280 km panjang — danau buatan terbesar dunia dengan kapal kasino."]},
}

fc=0
for code in D:
 p=f'{DIR}/{code}.json'
 if not os.path.exists(p):continue
 d=json.load(open(p))
 ch=False
 for field in ['keuntungan_geografis','kerugian_geografis','fakta_unik']:
  old=d.get(field,[])
  if code in D and field in D[code] and any(hg(i) for i in old):
   d[field]=D[code][field];ch=True
 if ch:
  d['terakhir_diubah']=T
  json.dump(d,open(p,'w'),indent=2,ensure_ascii=False)
  fc+=1;print(f'Fixed {code}')
print(f'Total fixed part2: {fc}')
