import json,os,sys
DIR='data/curated';T='2026-07-27'
G=['menunjukkan betapa beragamnya kondisi geografis','menyimpan cerita menarik tentang bagaimana geografi','dapat fokus pada niche ekonomi spesialis','ketergantungan pada impor','Sebagai negara mikro','rentan terhadap badai tropis/siklon','menjadi modal pembangunan berkelanjutan','Memiliki akses ke laut/samudra memberikan','Ukuran compact','garis pantai yang sepenuhnya dikelola','peluang perdagangan maritim, perikanan, dan pelabuhan','negara kepulauan/pulau','menghadapi tantangan RUANG HIDUP','(meski jenisnya berbeda-beda)']
def hg(t):return any(p in t for p in G)

DATA={
"AE":{"keuntungan_geografis":["Uni Emirat Arab di Teluk Persia dengan 1.318 km garis pantai menguasai Selat Hormuz — jalur minyak tersibuk dunia, 20% minyak global melewatinya.","Cadangan minyak UEA terbesar ke-7 dunia (98 miliar barrel) dan gas alam terbesar ke-6 — keuntungan ekonomi geopolitik luar biasa.","Posisi di Timur Tengah menjadikan Dubai dan Abu Dhabi hub penerbangan global — Bandara Dubai tersibuk ke-3 dunia."],"kerugian_geografis":["Lebih 80% wilayah gurun pasir Rub al Khali, suhu mencapai 50 derajat Celcius — 99% air minum dari desalinasi.","Tidak punya sungai permanen atau danau — air berasal dari desalinasi dan akuifer yang semakin menipis."]},
"AI":{"keuntungan_geografis":["Anguilla di Karibia timur dengan 33 pulau karang berpasir putih — dekat Puerto Rico memudahkan akses wisatawan.","Perairan dangkal ideal budidaya lobster dan ikan karang — ekosistem terumbu karang menarik penyelam dunia.","Status Wilayah Seberang Laut Britania memberikan stabilitas politik dan mata uang dipatok ke USD."]},
"AT":{"keuntungan_geografis":["Posisi Austria di jantung Eropa Tengah dan lembah Sungai Danube menjadikannya koridor transportasi darat vital.","Alps Austria menutupi 62% wilayah, menyediakan resort ski kelas dunia dan sumber air bersih melimpah.","Iklim sedang di lembah Danube mendukung pertanian anggur — wine region Wachau dan Gruner Veltliner terkenal."]},
"BB":{"keuntungan_geografis":["Barbados di ujung timur Karibia, 97 km garis pantai — Carlisle Bay tenang dan Bathsheba bergelombang untuk surfing.","Iklim tropis 24-30 derajat Celcius sepanjang tahun dan 3.000 jam sinar matahari — destinasi wisata premium.","Perairan Karibia di sekitar Barbados mendukung perikanan ikan terbang (flying fish) — ikan nasional Barbados."]},
"BE":{"keuntungan_geografis":["Belgia di persimpangan Eropa Barat berbatasan 4 negara — Brussels jadi ibu kota EU dan NATO.","Pelabuhan Antwerp pelabuhan kedua terbesar Eropa dan pusat perdagangan berlian terbesar dunia.","Tanah Flanders datar subur mendukung pertanian intensif — pengekspor produk pertanian per kapita tertinggi EU."]},
"BF":{"keuntungan_geografis":["Burkina Faso di tengah Afrika Barat berbatasan 6 negara — posisi transit perdagangan regional Sahel.","Dataran tinggi Mossi (300-400 m) menyediakan lahan untuk pertanian jagung, milet, dan sorghum.","Sungai Mouhoun (Volta Merah) mengalir ke Danau Volta Ghana — potensi irigasi dan energi hidro."]},
"BH":{"keuntungan_geografis":["Bahrain kepulauan 33 pulau di tengah Teluk Persia — posisi strategis antara Arab Saudi dan Qatar.","Teluk Bahrain dangkal hangat, habitat terumbu karang terbaik Teluk Persia dengan 300+ spesies ikan.","Jembatan King Fahd (25 km) menghubungkan Bahrain ke Arab Saudi — satu-satunya jembatan lintas negara di Teluk."]},
"BI":{"keuntungan_geografis":["Burundi di cekungan Danau Tanganyika — danau terdalam ke-2 dunia (1.470 m) menyediakan ikan dan jalur air.","Iklim tropis dataran tinggi (1.400-1.800 m) di pegunungan Kongo-Nil ideal untuk kopi dan teh berkualitas.","Sumber mata air di pegunungan Kongo-Nil mengalir ke dua cekungan sungai terbesar Afrika — Kongo dan Nil."]},
"BL":{"keuntungan_geografis":["Saint Barthelemy di Lesser Antilles dengan pantai pasir putih dan perairan biru jernih — destinasi wisata mewah.","Teluk terlindung Gustavia Harbor menyediakan pelabuhan alami untuk yacht dan kapal pesiar mega.","Terumbu karang sekitar pulau habitat 180+ spesies ikan dan 40+ spesies karang — surga diving."]},
"BN":{"keuntungan_geografis":["Brunei di pantai utara Kalimantan menghadap Laut Cina Selatan — posisi strategis jalur perdagangan Asia Tenggara.","Hutan hujan tropis menutupi 72% wilayah — tutupan hutan tertinggi di Asia Tenggara.","Cadangan minyak dan gas lepas pantai Brunei sangat besar — sekitar 300.000 barrel minyak per hari."]},
"BO":{"keuntungan_geografis":["Danau Titicaca di perbatasan Bolivia-Peru — danau navigasi tertinggi dunia (3.812 m) batas alami.","Keberagaman dari Andes bersalju (6.500+ m) hingga hutan Amazon — 6 dari 8 zona iklim dunia ada di Bolivia.","Salar de Uyuni dataran garam terbesar dunia (10.582 km persegi) mengandung 50-70% cadangan litium dunia."]},
"BW":{"keuntungan_geografis":["Delta Okavango delta pedalaman terbesar dunia (15.000 km persegi) — surga satwa liar dan UNESCO.","Posisi stabil di tengah Afrika Selatan jauh dari pantai — keamanan geopolitik unik di kawasan.","Gurun Kalahari (70% wilayah) mengandung berlian — produsen berlian terbesar berdasarkan nilai."]},
"CF":{"keuntungan_geografis":["Republik Afrika Tengah di jantung benua berbatasan 6 negara — posisi sentral perdagangan regional.","Hutan hujan tropis selatan menyimpan 3.600+ spesies tumbuhan dan 209 spesies mamalia.","Sungai Ubangi dan Sangha mengalir ke Sungai Kongo — sistem sungai terbesar kedua di dunia."]},
"CI":{"keuntungan_geografis":["Pantai Gading menghadap Teluk Guinea 515 km garis pantai — pelabuhan Abidjan terbesar Afrika Barat.","Hutan tropis selatan 25% hutan Afrika Barat — produsen kakao terbesar dunia (40% supply global).","Sungai Como, Bandama, dan Cavally menyediakan irigasi untuk perkebunan karet dan kakao."]},
"CM":{"keuntungan_geografis":["Garis pantai 402 km di Teluk Guinea — pelabuhan Douala terbesar Afrika Tengah.","Gunung Kamerun (4.095 m) gunung berapi tertinggi Afrika Barat — dari tropis hingga alpine dalam satu gunung.","Kamerun disebut Afrika Mini — pantai, hutan, sabana, gunung, dan danau dalam satu negara."]},
"CU":{"keuntungan_geografis":["Pulau terbesar Karibia (109.884 km persegi) di mulut Teluk Meksiko mengontrol jalur laut ke Florida.","Ladang tembakau Pinar del Rio (Vuelta Abajo) menghasilkan tembakau tertinggi — bahan cerutu Cohiba.","Terumbu karang Kuba terbesar di Karibia — 2.000+ spesies ikan dan 50+ spesies karang."]},
"CV":{"keuntungan_geografis":["Kepulauan Tanjung Verde 570 km lepas pantai Afrika Barat — posisi strategis di tengah Atlantik.","Angin dagang konsisten ideal energi angin — 30% listrik dari pembangkit angin.","Perairan kaya ikan tuna — perikanan 80% ekspor dan tulang punggung ekonomi kepulauan."]},
"ER":{"keuntungan_geografis":["Garis pantai 2.234 km di Laut Merah dengan 350+ pulau — salah satu terpanjang di Afrika.","Pelabuhan Massawa menghadap jalur pelayaran Laut Merah — 12% perdagangan global melewatinya.","Dankalia Depression salah satu tempat terpanas di bumi — potensi besar energi panas bumi (geothermal)."]},
"FJ":{"keuntungan_geografis":["Fiji 333 pulau di Pasifik Selatan — posisi strategis sebagai hub penerbangan antar benua.","Terumbu karang 4.000 mil persegi dan laguna luas di Pasifik Selatan — surga diving kelas dunia.","Hutan tropis menutupi 56% Fiji — sumber kayu keras dan keanekaragaman hayati endemik tinggi."]},
"FM":{"keuntungan_geografis":["Mikronesia 607 pulau di Pasifik barat — masing-masing negara bagian punya karakter unik.","Chuuk Lagoon punya 50+ bangkai kapal Perang Dunia II — tujuan penyelaman sejarah terbaik Pasifik.","Reruntuhan Nan Madol di Pohnpei — kota kuno di atas terumbu karang dikenal sebagai Venice Pasifik."]},
"GD":{"keuntungan_geografis":["Grenada di Karibia selatan 121 km garis pantai — pelabuhan alami St. George terlindung.","Gunung St. Catherine (840 m) tanah vulkanik subur — Grenada produsen utama pala dunia.","Terumbu karang sekitar Grenada habitat penyu dan lumba-lumba — menarik wisata bahari."]},
"GM":{"keuntungan_geografis":["Gambia mengapung di sepanjang Sungai Gambia (1.120 km) — sungai navigasi membelah negara timur-barat.","Pesisir Atlantik 80 km — akses langsung jalur perdagangan maritim Afrika Barat.","Tanah aluvial sungai subur untuk pertanian — kacang tanah (groundnut) komoditas ekspor utama."]},
"GW":{"keuntungan_geografis":["Guinea-Bissau pesisir Afrika Barat 350 km garis pantai dan Kepulauan Bissagos (88 pulau).","Hutan mangrove terbesar Afrika Barat menutupi pesisir — habitat kura-kura, buaya, dan ikan tropis.","Arsipelago Bissagos masyarakat matriarchal — budaya Bijagos unik dan ekosistem terjaga."]},
"HM":{"keuntungan_geografis":["Pulau Heard dan McDonald di Samudra Hindia selatan — salah satu tempat paling terisolasi di bumi.","Gunung Mawson (2.745 m) gunung berapi aktif — ekosistem sub-Antartika hampir tidak tersentuh.","Perairan kaya krill dan plankton — mendukung anjing laut, gajah laut, dan penguin."]},
"IO":{"keuntungan_geografis":["Teritorial Samudra Hindia Britania mencakup Kepulauan Chagos — atol Diego Garcia pangkalan militer strategis.","Perairan sekitar atol kaya terumbu karang — ekosistem laut hampir tidak tersentuh manusia.","Posisi di tengah Samudra Hindia menguasai jalur pelayaran Timur Tengah-Asia Pasifik."]},
"JM":{"keuntungan_geografis":["Jamaika di Karibia utara 1.022 km garis pantai — Negril dan Montego Bay destinasi wisata terkenal.","Blue Mountains (2.256 m) menghasilkan kopi Blue Mountain — salah satu kopi termahal dunia.","Posisi dekat Kuba dan Hispaniola menjadikan Jamaica transit point penting di Karibia."]},
"JO":{"keuntungan_geografis":["Yordania menguasai sebagian Laut Mati — titik terendah daratan bumi (minus 430 m) kaya mineral potas.","Gurun Wadi Rum dengan formasi batu pasir merah — lokasi syuting film dan destinasi hiking.","Posisi antara Arab Saudi, Irak, dan Israel membuat Yordania koridor diplomatik penting Timur Tengah."]},
"KH":{"keuntungan_geografis":["Kamboja di semenanjung Indochina dengan Teluk Thailand 443 km garis pantai.","Danau Tonle Sap danau air tawar terbesar Asia Tenggara — membesar 5x saat musim hujan.","Sungai Mekong mengalir melalui Kamboja 500 km — sumber ikan dan irigasi vital."]},
"KI":{"keuntungan_geografis":["Kiribati 33 atol tersebar di 3,5 juta km persegi Samudra Pasifik — zona ekonomi eksklusif sangat luas.","Perairan kaya tuna dan ikan pelagis — lisensi perikanan sumber pendapatan utama.","Atol Kiritimati (Christmas Island) atol karang terbesar dunia — habitat burung laut dan spesies endemik."]},
"KM":{"keuntungan_geografis":["Komoro kepulauan di Selat Mozambik antara Afrika timur dan Madagaskar — posisi maritim strategis.","Gunung Karthala (2.361 m) gunung berapi aktif terbesar di Samudra Hindia barat — tanah vulkanik subur.","Perairan Komoro habitat 200+ spesies ikan karang dan terumbu karang yang masih pristin."]},
"LA":{"keuntungan_geografis":["Laos SATU-SATUNYA negara daratan terkurung di Asia Tenggara — Sungai Mekong sebagai jalur utama.","Sungai Mekong membentuk perbatasan alami 1.835 km dengan Thailand dan Myanmar.","Pegunungan Annam di timur dan Mekong di barat menyediakan keanekaragaman ekosistem."]},
"LC":{"keuntungan_geografis":["Santa Lucia di Karibia timur dengan Pitons — dua puncak vulkanik ikonik yang menjadi Situs Warisan Dunia.","Iklim tropis dan perairan jernih menjadikan Santa Lucia destinasi wisata premium di Lesser Antilles.","Pantai Anse Chastanet dan Jalousie di antara Pitons — salah satu pantai terindah Karibia."]},
"LK":{"keuntungan_geografis":["Sri Lanka di Samudra Hindia 1.340 km garis pantai — posisi strategis di jalur pelayaran Asia-Eropa.","Puncak Pidurutalagala (2.524 m) di tengah pulau menciptakan zona iklim berbeda dalam 65.000 km persegi.","Tanah dataran barat daya subur untuk teh — Sri Lanka pengekspor teh Ceylon terkenal dunia."]},
"MF":{"keuntungan_geografis":["Saint Martin bagian utara (Prancis) hanya 53 km persegi — pulau terkecil di dunia yang dibagi dua negara.","Teluk Marigot dan Grand Case menyediakan pelabuhan alami untuk yacht dan kapal pesiar.","Terumbu karang sekitar pulau habitat penyu dan lumba-lumba — menarik wisata bahari premium."]},
"MG":{"keuntungan_geografis":["Madagaskar pulau terbesar ke-4 di dunia (587.000 km persegi) — terpisah dari Afrika 160 juta tahun lalu.","90% spesies di Madagaskar ENDEMIK — lemur, baobab, dan fossa tidak ditemukan di tempat lain.","Pesisir barat Tsingy de Bemaraha formasi batu kapur tajam — Situs Warisan Dunia UNESCO."]},
}

# kerugian + fakta_unik for ALL above
KR_FU={
"AE":{"kerugian_geografis":["Lebih 80% wilayah gurun Rub al Khali, suhu mencapai 50 derajat Celcius — 99% air minum dari desalinasi.","Tidak punya sungai permanen atau danau — air berasal dari desalinasi dan akuifer yang semakin menipis."],"fakta_unik":["Dubai punya BANGUNAN TERTINGGI dunia Burj Khalifa (828 m) dan Palm Jumeirah terlihat dari luar angkasa.","Abu Dhabi membangun kota Masdar — kota nol karbon pertama tanpa mobil sepenuhnya bertenaga surya.","UEA punya 200+ pulau alami dan buatan — Sir Bani Yas diubah jadi cagar alam margasatwa."]},
"AI":{"kerugian_geografis":["Pulau karang datar ketinggian maks 65 m — sangat rentan kenaikan permukaan laut dan badai Karibia.","Tidak punya sumber air tawar alami — bergantung penampungan hujan dan desalinasi."],"fakta_unik":["Anguilla terkenal dengan domba kalapahing yang dibawa kolonialis Prancis 1600-an.","Pulau 26 km panjang 5 km lebar — teritori terkecil dengan populasi sekitar 15.000.","Scilly Cay lepas pantai Anguilla destinasi makanan laut terbaik di Karibia timur."]},
"AT":{"kerugian_geografis":["Negara daratan terkurung tanpa akses laut — bergantung negara tetangga untuk perdagangan maritim.","Alps menyulitkan infrastruktur — beberapa lembah terisolasi saat musim dingin."],"fakta_unik":["Austria punya 13.000 danau alpine — kepadatan danau tertinggi di dunia.","Sungai Danube mengalir 350 km melintasi Wina — jalur perdagangan sejak Kekaisaran Romawi.","Gletser Pasterze di Grossglockner (3.798 m) menyusut 90% sejak 1850 akibat perubahan iklim."]},
"BB":{"kerugian_geografis":["Pulau karang datar Mount Hillaby hanya 340 m — rentan erosi pantai dan kenaikan permukaan laut.","Lahan pertanian terbatas di 430 km persegi — ketergantungan pada impor bahan pangan."],"fakta_unik":["Barbados SATU-SATUNYA pulau karang di Karibia timur — lainnya dari gunung berapi.","Teluk Carlisle punya 200 bangkai kapal terendam — tujuan penyelaman sejarah terbaik Karibia.","Harrison Cave jaringan gua terbesar Karibia dengan stalaktit dan stalagmit spektakuler."]},
"BE":{"kerugian_geografis":["Wilayah kecil (30.528 km persegi) padat (376/km persegi) — seluruh negara lebih kecil dari Jawa Barat.","Tidak punya fitur geografis pertahanan — dataran menyebabkan Belgia medan invasi berulang."],"fakta_unik":["Belgia punya 3 wilayah geografis berbeda — Dataran Pesisir, Tengah, dan Tinggi Ardennes.","Sungai Meuse dan Scheldt jalan tol air Eropa ke pelabuhan Antwerp dan Rotterdam.","Tripoin Belgia-Belanda-Jerman dekat Aachen salah satu yang paling terkenal di Eropa."]},
"BF":{"kerugian_geografis":["Terkurung darat di Sahel — salah satu paling jauh dari laut, tidak punya pantai.","Sahara menggusur wilayah subur (desertifikasi) — mengancam pertanian 80% penduduk."],"fakta_unik":["Tebing Sindou formasi batu pasir merah 100 m — Grand Canyon Afrika Barat.","Sungai Mouhoun satu-satunya sungai permanen — lainnya hanya mengalir musiman Juni-September.","Pohon baobab 1.500+ tahun di dekat Ouahigouya — salah satu tertua di Afrika Barat."]},
"BH":{"kerugian_geografis":["Pulau kecil (780 km persegi) air tawar terbatas — sebagian besar dari desalinasi.","Datar (titik tertinggi 134 m) sebagian lahan direklamasi dari laut, rentan kenaikan laut."],"fakta_unik":["Pohon Kehidupan Bahrain — mesquite 400+ tahun tumbuh di gurun tanpa sumber air terlihat.","Nama Bahrain dari bahasa Arab artinya dua laut — mata air tawar di bawah laut asin dimanfaatkan 5.000 tahun.","Bahrain negara pertama Teluk Persia temukan minyak (1932) — sekarang hub keuangan Islam."]},
"BI":{"kerugian_geografis":["Terkurung darat dan terpadat di Afrika (463/km persegi) — tekanan lahan erosi parah.","Topografi berbukit curam menyebabkan erosi masif — lahan pertanian berkurang akibat longsor."],"fakta_unik":["Burundi berbagi Danau Tanganyika perbatasan alami dengan Tanzania dan Kongo.","Sumber Sungai Ruvubu di utara Burundi salah satu mata air Sungai Nil.","Dataran tinggi rata-rata 1.700 m — disebut Negara Seribu Bukit bersama Rwanda."]},
"BL":{"kerugian_geografis":["Pulau sangat kecil (21 km persegi) — bergantung penampungan hujan dan impor air.","Hurricane Irma 2017 menghancurkan sebagian besar bangunan di pulau ini."],"fakta_unik":["Saint Barthelemy satu-satunya wilayah Karibia berbudaya Swedia — 1784-1878.","Pantai Shell Beach ditutupi jutaan kerang — pantai pasir kerang unik di dunia.","Gustavia dinamai Raja Gustav III Swedia — fortifikasi Swedia masih terlihat."]},
"BN":{"kerugian_geografis":["Negara kecil (5.765 km persegi) terkurung dalam Malaysia (Sarawak).","Penduduk di pesisir dataran rendah — rentan kenaikan permukaan laut dan banjir rob."],"fakta_unik":["Istana Nurul Iman ISTANA TERBESAR dunia — 1.788 kamar dan 257 kamar mandi.","Taman Ulu Temburong hutan hujan tertua Borneo — hanya bisa diakses perahu panjang.","Kampung Ayer desa terapung terbesar dunia — 30.000+ penduduk di rumah panggung atas air."]},
"BO":{"kerugian_geografis":["Kehilangan akses laut setelah Perang Pasifik 1879-1883 — Chili merebut pesisirnya.","Andes menyebabkan isolasi — perjalanan antar kota bisa berhari-hari."],"fakta_unik":["Salar de Uyuni cermin alami terbesar — air tipis di atas garam memantulkan langit sempurna.","Danau Titicaca danau tertinggi dilayari kapal — rumah orang Uros di pulau totora.","Nevado Sajama (6.542 m) gunung tertinggi Bolivia dengan gletser tropis tertinggi Andes."]},
"BW":{"kerugian_geografis":["Terkurung darat, 70% gurun Kalahari — akses air bersih terbatas.","Musim kering 8 bulan menyebabkan kekeringan berkala mengancam pertanian dan satwa."],"fakta_unik":["Delta Okavango satu-satunya delta besar yang mengalir ke daratan — air Angola menghilang di pasir.","Makgadikgadi Pan gurun garam 12.000 km persegi — habitat migrasi zebra terbesar kedua Afrika.","Populasi gajah liar terbesar dunia (130.000+) berkonsentrasi di Taman Nasional Chobe."]},
"CF":{"kerugian_geografis":["Terkurung darat di tengah Afrika — akses laut memerlukan perjalanan lewat negara tetangga.","Hanya 700 km jalan beraspal di seluruh negara — infrastruktur sangat minim."],"fakta_unik":["Air terjun Boali 50 m tinggi 250 m lebar — terbesar di Republik Afrika Tengah.","Dzanga-Sangha salah satu dari sedikit tempat gorila dataran rendah bisa diamati.","Kubah granit 1.000 m di dataran tinggi Bongo — disebut kubah gajah raksasa."]},
"CI":{"kerugian_geografis":["Perbatasan selatan laguna dan rawa — banjir musiman mengancam Abidjan.","Deforestasi 80% hutan hilang sejak 1960 — erosi akibat perluasan perkebunan kakao."],"fakta_unik":["Parit Assinie saluran air alami 30 km membelah laguna Ebrie — jalur navigasi unik.","Taman Nasional Tai hutan hujan primer terbesar Afrika Barat — Situs Warisan Dunia.","Basilika Yamoussoukro kubah 158 m — gereja Kristen terbesar melampaui St. Peter Vatikan."]},
"CM":{"kerugian_geografis":["Hutan hujan selatan menyulitkan infrastruktur — jalan sangat mahal.","Gunung Kamerun AKTIF — letusan 2000, gas CO2 Danau Nyos 1986 menewaskan 1.700."],"fakta_unik":["Danau Nyos meletuskan CO2 1986 — limnic eruption menewaskan 1.746 orang.","Gunung Kamerun naik langsung dari Atlantik — satu-satunya gunung berapi aktif Afrika di tepi laut.","Waza National Park habitat singa, gajah, jerapah — taman nasional terbaik Afrika Barat."]},
"CU":{"kerugian_geografis":["Di jalur hurricane — 1-2 badai besar per tahun, kerusakan miliaran dolar.","Blokade ekonomi AS 60+ tahun membatasi akses perdagangan internasional."],"fakta_unik":["Kuba punya LEBIH BANYAK DOKTER per kapita dari negara mana pun — 8,2 per 1.000 penduduk.","Zapata Swamp (4.500 km persegi) rawa terbesar Karibia — habitat buaya Kuba endemik.","Kuba satu-satunya negara komunis di Karibia dan salah satu dari sedikit di hemisphere barat."]},
"CV":{"kerugian_geografis":["Sumber air tawar sangat terbatas — kekeringan berkepanjangan sejak 1960.","Terpencil di tengah Atlantik — biaya transportasi tinggi, rentan badai tropis."],"fakta_unik":["Tanjung Verde negara pulau paling kering Afrika — pulau selatan hampir gurun.","Pico do Fogo (2.829 m) gunung berapi AKTIF — letusan 2014 evakuasi seluruh pulau.","Awalnya TIDAK BERPENDUDUK — ditemukan Portugis 1456 sebagai basis perdagangan budak."]},
"ER":{"kerugian_geografis":["80% gurun dan semi-gurun — hanya 5% lahan bisa ditanami.","Ibu kota Asmara di dataran tinggi 2.325 m terisolasi dari pesisir oleh pegunungan."],"fakta_unik":["Dankalia Depression titik terendah Afrika di bawah permukaan laut.","Massawa di pesisir dan Asmara di dataran tinggi — perbedaan suhu 15 derajat dalam 100 km.","Eritrea punya 350+ pulau di Laut Merah — banyak belum dijelajahi."]},
"FJ":{"kerugian_geografis":["Kepulauan terpencil Pasifik Selatan — biaya logistik sangat tinggi.","Beberapa pulau aktif vulkanik — Taveuni punya gunung berapi aktif dan gempa."],"fakta_unik":["Fiji 333 pulau tapi hanya 110 dihuni — banyak yang masih alami.","Taveuni Garden Island 80% hutan hujan primer dengan waterfall Tavoro spektakuler.","Fiji negara pertama Pasifik yang menerima pengungsi iklim dari Kiribati dan Tuvalu."]},
"FM":{"kerugian_geografis":["Kepulauan sangat terpencil 2.900 km dari Hawaii — transportasi dan logistik mahal.","Garis pantai rendah (rata-rata 2 m) rentan kenaikan permukaan laut."],"fakta_unik":["Nan Madol di Pohnpei kota kuno 92 pulau buatan — Venice Pasifik UNESCO.","Chuuk Lagoon armada Jepang karam 50+ kapal jadi museum bawah laut.","Pulau Yap terkenal batu rai — uang batu raksasa hingga 3,6 m diletakkan di jalan."]},
"GD":{"kerugian_geografis":["Hurricane Ivan 2004 menghancurkan 90% bangunan — rentan badai Karibia.","Pulau kecil (344 km persegi) ekonomi bergantung satu komoditas pala."],"fakta_unik":["Grenada Spice Isle — produsen pala terbesar kedua dunia setelah Indonesia.","Grand Anse Beach 3 km — salah satu pantai terbaik Karibia.","Underwater Sculpture Park Grenada pertama di dunia — patung bawah laut jadi terumbu karang buatan."]},
"GM":{"kerugian_geografis":["Negara terkecil daratan Afrika (10.689 km persegi) — dikelilingi Senegal kecuali pesisir.","Sungai Gambia banjir musim hujan — daerah rendah sepanjang sungai terendam berkala."],"fakta_unik":["Gambia NEGARA TERKECIL di daratan Afrika — panjang sempit mengikuti Sungai Gambia.","James Island Situs Warisan Dunia — bekas benteng perdagangan budak ke Amerika.","Kiang West National Park habitat kuda nil, hyena, 250+ burung di tepi Sungai Gambia."]},
"GW":{"kerugian_geografis":["Iklim muson hujan sangat basah Juni-Oktober — banjir menghambat transportasi.","Infrastruktur sangat minim — salah satu negara paling underdeveloped Afrika Barat."],"fakta_unik":["Kepulauan Bissagos 88 pulau masyarakat matriarchal — salah satu dari sedikit di dunia.","Hutan mangrove terbesar Afrika Barat — penting untuk penyerapan karbon global.","Delta Sungai Geba dan Corubal ideal pertanian padi dan perikanan tradisional."]},
"HM":{"kerugian_geografis":["80% permukaan tertutup gletser — tidak ada penduduk permanen.","Terpencil 4.000 km dari Australia — akses hanya beberapa bulan setahun."],"fakta_unik":["Pulau Heard SATU-SATUNYA gunung berapi aktif milik Australia — Big Ben meletus berkali-kali.","Seluruh wilayah UNESCO — salah satu dari sedikit tempat tanpa spesies invasif.","Marine Reserve terbesar Australia — rumah 43 spesies burung laut."]},
"IO":{"kerugian_geografis":["Atol dataran rendah (1-2 m) sangat rentan kenaikan permukaan laut.","Populasi Chagossian diusir 1967-1973 untuk pangkalan militer — isu HAM belum terselesaikan."],"fakta_unik":["Atol Diego Garcia salah satu atol terbesar dunia — lagunanya lebih besar dari Washington DC.","Perairan Chagos 220+ spesies karang dan 1.000+ ikan — biodiversitas laut tertinggi Samudra Hindia.","Chagos Marine Protected Area 640.000 km persegi dinyatakan 2010."]},
"JM":{"kerugian_geografis":["Karst limestone barat menyebabkan longsor dan erosi parah saat hujan deras.","Zona gempa dan jalur hurricane — gempa 1692 menghancurkan Port Royal ke dasar laut."],"fakta_unik":["Blue Mountain Peak (2.256 m) dari puncaknya bisa melihat KUBA 145 km di seberang laut.","Blue Hole Ocho Rios lubang gua alami di laut — spot diving paling terkenal Karibia.","Port Royal disapu gempa 1692 ke dasar laut — kini Situs Warisan Dunia bawah laut."]},
"JO":{"kerugian_geografis":["95% wilayah gurun dan semi-gurun — air sangat terbatas, salah satu paling kering di dunia.","Tidak punya cadangan minyak besar seperti tetangganya — bergantung bantuan asing."],"fakta_unik":["Laut Mati titik terendah bumi 430 m di bawah permukaan laut — 10x lebih asin dari laut biasa.","Petra di selatan Yordania kota batu Nabatean 2.000 tahun — salah satu Keajaiban Dunia Baru.","Wadi Rum gurun merah tempat film Lawrence of Arabia dan The Martian syuting."]},
"KH":{"kerugian_geografis":["Tidak punya pantai di Teluk Thailand yang lebar — akses maritim terbatas.","Sisa ranjau darat dari perang sipil menghambat pertanian di pedesaan."],"fakta_unik":["Danau Tonle Sap membesar 5x saat musim hujan — dari 2.500 jadi 16.000 km persegi.","Angkor Wat terbesar kompleks keagamaan di dunia — dibangun di dataran rendah Kamboja.","Sungai Mekong mengalir 500 km di Kamboja — menyediakan 80% protein ikan penduduk."]},
"KI":{"kerugian_geografis":["Atol rata-rata hanya 2 m di atas laut — kenaikan permukaan laut ancaman eksistensial.","Terpencil di Pasifik tengah — biaya transportasi dan logistik sangat tinggi."],"fakta_unik":["Kiritimati (Christmas Island) atol terbesar dunia — 388 km persegi dengan laguna raksasa.","Kiribati menjadi negara pertama yang MEMBELI tanah di Fiji sebagai pengungsi iklim.","Pulau Banaba hancur oleh pertambangan fosfat — seluruh permukaan digali selama 80 tahun."]},
"KM":{"kerugian_geografis":["Kepulauan kecil (2.236 km persegi) dengan sumber daya alam sangat terbatas.","Gunung Karthala aktif — letusan 2005 mengancam ibu kota Moroni."],"fakta_unik":["Komoro berasal dari kata Arab Djazair al-Komor — Kepulauan Bulan.","Hewan endemik Livingstone fruit bat (kelelawar buah) hanya ada di Komoro.","Perairan Komoro habitat hiu paus — salah satu tempat terbaik di dunia melihat hiu paus."]},
"LA":{"kerugian_geografis":["Tidak punya akses laut — satu-satunya negara daratan terkurung di Asia Tenggara.","Pegunungan terjal menyulitkan transportasi dan pembangunan infrastruktur."],"fakta_unik":["Sungai Mekong 4.350 km dari Tibet ke Vietnam — 1.835 km membentuk perbatasan Laos.","Dateng Ban Viengxay gua tersembunyi tempat Pathet Lao berlindung selama Perang Vietnam.","Laos punya air terjun Khone Phapheng — air terjun terlebar di dunia di Sungai Mekong."]},
"LC":{"kerugian_geografis":["Pulau kecil (617 km persegi) dengan ekonomi bergantung pada pariwisata.","Rentan badai dan hurricane Karibia — kerusakan signifikan tiap dekade."],"fakta_unik":["Pitons dua puncak vulkanik Gros Piton (770 m) dan Petit Piton (743 m) — Situs Warisan Dunia.","Drive-in Volcano Soufriere satu-satunya drive-in volcano di dunia — pengunjung bisa mendekati kawah.","Santa Lucia mengubah ekonomi dari pertanian ke pariwisata — salah satu sukses story Karibia."]},
"LK":{"kerugian_geografis":["Pulau terpencil di Samudra Hindia — tsunami 2004 menewaskan 35.000 orang di sri lanka.","Perang saudara 26 tahun menghambat pengembangan wilayah utara dan timur."],"fakta_unik":["Sri Lanka disebut Tear of India — bentuk tetesan air di ujung selatan India.","Sigiriya bebatuan vulkanik 200 m dengan istana kuno di puncak — Benteng di Langit.","Sri Lanka punya tertinggi kepadatan gajah liar di Asia — Minneriya Safari terkenal."]},
"MF":{"kerugian_geografis":["Pulau kecil (53 km persegi) sumber air dan lahan sangat terbatas.","Badai Karibia merusak secara berkala — Hurricane Irma 2017 penghancuran besar."],"fakta_unik":["Saint Martin pulau terkecil di dunia dibagi dua negara — Prancis utara, Belanda selatan.","Orient Beach terkenal di Karibia — pantai berpakaian opsional dan restoran mewah.","Saint Martin punya laguna terbesar di Karibia — 10 km persegi perairan dangkal tenang."]},
"MG":{"kerugian_geografis":["Pulau besar tapi infrastruktur sangat minim — hanya 15% jalan beraspal.","Deforestasi masif — 90% hutan asli hilang, erosi tanah parah di dataran tinggi."],"fakta_unik":["Madagaskar terpisah dari Afrika 160 juta tahun — evolusi unik menghasilkan spesies endemik.","Avenue of Baobab di Morondava deretan pohon baobab raksasa ikonik dunia.","Tsingy de Bemaraha formasi batu kapur tajam — disebut hutan batu, UNESCO."]},
}

fc=0
for code in DATA:
    p=f'{DIR}/{code}.json'
    if not os.path.exists(p):continue
    d=json.load(open(p))
    ch=False
    for field in ['keuntungan_geografis','kerugian_geografis','fakta_unik']:
        old=d.get(field,[])
        new=[]
        for it in old:
            if hg(it):
                if code in DATA and field in DATA[code]: new.append(DATA[code][field][0]) if len(new)<len(DATA[code].get(field,[])) else new.append(it)
                elif code in KR_FU and field in KR_FU[code]: new.append(KR_FU[code][field][0]) if len(new)<len(KR_FU[code].get(field,[])) else new.append(it)
                else: new.append(it)
            else: new.append(it)
        # If we have proper data for this field, replace entire field
        if code in DATA and field in DATA[code] and any(hg(i) for i in old):
            new=DATA[code][field]
            ch=True
        elif code in KR_FU and field in KR_FU[code] and any(hg(i) for i in old):
            new=KR_FU[code][field]
            ch=True
        d[field]=new
    if ch:
        d['terakhir_diubah']=T
        json.dump(d,open(p,'w'),indent=2,ensure_ascii=False)
        fc+=1
        print(f'Fixed {code}')
print(f'Total fixed: {fc}')
