#!/usr/bin/env python3
"""Phase 3 ALL-IN-ONE: Fix content, names, and youtube_ids."""
import json, os, re, time

DIR = 'data/curated'
TODAY = '2026-07-27'

GENERIC = [
    'menunjukkan betapa beragamnya kondisi geografis',
    'menyimpan cerita menarik tentang bagaimana geografi',
    'dapat fokus pada niche ekonomi spesialis',
    'ketergantungan pada impor',
    'Sebagai negara mikro',
    'rentan terhadap badai tropis/siklon',
    'menjadi modal pembangunan berkelanjutan',
    'Memiliki akses ke laut/samudra memberikan',
    'Ukuran compact',
    'garis pantai yang sepenuhnya dikelola',
    'peluang perdagangan maritim, perikanan, dan pelabuhan',
    'negara kepulauan/pulau',
    'menghadapi tantangan RUANG HIDUP',
]

def has_generic(text):
    return any(p in text for p in GENERIC)

# ==================== CONTENT DATA ====================
DATA = {"AE": {"keuntungan_geografis": ["Uni Emirat Arab terletak di Teluk Persia dengan garis pantai 1.318 km, menguasai Selat Hormuz — jalur minyak tersibuk dunia yang dilalui 20% minyak global.", "Cadangan minyak bumi UEA terbesar ke-7 dunia (98 miliar barrel) dan gas alam terbesar ke-6 memberikan keuntungan ekonomi geopolitik luar biasa.", "Posisi strategis di Timur Tengah menjadikan Dubai dan Abu Dhabi hub penerbangan dan logistik global — Bandara Dubai tersibuk ke-3 dunia."], "kerugian_geografis": ["Lebih dari 80% wilayah UEA adalah gurun pasir (Rub al Khali) dengan suhu mencapai 50 derajat Celcius — air tawar sangat terbatas, 99% air minum dari desalinasi.", "Tidak memiliki sungai permanen atau danau alami — seluruh kebutuhan air berasal dari desalinasi laut dan akuifer bawah tanah yang semakin menipis."], "fakta_unik": ["Dubai memiliki BANGUNAN TERTINGGI di dunia Burj Khalifa (828 m), serta Palm Jumeirah yang merupakan pulau buatan terbesar terlihat dari luar angkasa.", "Abu Dhabi membangun kota Masdar — kota nol karbon pertama di dunia yang dirancang tanpa mobil dan sepenuhnya bertenaga surya.", "UEA memiliki lebih dari 200 pulau alami dan buatan, termasuk Sir Bani Yas yang diubah menjadi cagar alam margasatwa."]},
"AI": {"keuntungan_geografis": ["Anguilla terletak di Karibia timur dengan 33 pulau karang berpasir putih — surga wisata bahari mewah dekat Puerto Rico.", "Perairan dangkal ideal untuk budidaya lobster dan ikan karang, mendukung ekosistem terumbu karang yang menarik penyelam dunia.", "Status Wilayah Seberang Laut Britania memberikan stabilitas politik dan mata uang yang dipatok ke USD."], "kerugian_geografis": ["Pulau karang datar (ketinggian maks 65 m) sangat rentan terhadap kenaikan permukaan laut dan badai Karibia (Juni-November).", "Tidak memiliki sumber air tawar alami — bergantung penuh pada penampungan air hujan dan desalinasi."], "fakta_unik": ["Anguilla terkenal dengan domba kalapahing yang diperkirakan dibawa kolonialis Prancis pada 1600-an.", "Pulau ini hanya 26 km panjang dan 5 km lebar — salah satu teritori terkecil di dunia dengan populasi sekitar 15.000 jiwa.", "Anguilla memiliki perairan dangkal ditutupi rumput laut yang mendukung penyu hijau dan penyu sisik."]},
"AT": {"keuntungan_geografis": ["Posisi Austria di jantung Eropa Tengah dan lembah Sungai Danube menjadikannya koridor transportasi darat utama antara Eropa Barat dan Timur.", "Pegunungan Alpen menutupi 62% wilayah Austria, menyediakan resor ski kelas dunia (Kitzbuhel, St. Anton) dan sumber air bersih.", "Iklim kontinental sedang di lembah Danube mendukung pertanian anggur berkualitas — wine region Wachau terkenal dunia."], "kerugian_geografis": ["Negara daratan terkurung tanpa akses laut langsung — bergantung pada negara tetangga untuk perdagangan maritim.", "Topografi pegunungan Alpen menyulitkan pembangunan infrastruktur dan menyebabkan beberapa lembah terisolasi saat musim dingin."], "fakta_unik": ["Austria memiliki proporsi hutan tertinggi di EU — 47% wilayahnya ditutupi hutan.", "Sungai Danube mengalir 350 km di Austria — melintasi Wina dan menjadi jalur perdagangan sejak Kekaisaran Romawi.", "Gletser Pasterze di Grossglockner (3.798 m) adalah gletser terbesar Austria, menyusut 2,5 km sejak 1850."]},
"BB": {"keuntungan_geografis": ["Barbados di ujung timur Karibia punya 97 km garis pantai — pantai barat tenang (Carlisle Bay) dan timur bergelombang (Bathsheba) untuk surfing.", "Iklim tropis 24-30 derajat Celcius sepanjang tahun dengan 3.000 jam sinar matahari menjadikan Barbados destinasi wisata premium.", "Perairan Karibia di sekitar Barbados mendukung perikanan ikan terbang (flying fish) — ikan nasional Barbados."], "kerugian_geografis": ["Pulau karang datar (Mount Hillaby hanya 340 m) rentan terhadap erosi pantai dan kenaikan permukaan laut.", "Lahan pertanian terbatas di wilayah 430 km persegi — ketergantungan pada impor bahan pangan."] , "fakta_unik": ["Barbados adalah SATU-SATUNYA pulau karang di Karibia timur — lainnya berasal dari gunung berapi.", "Teluk Carlisle memiliki sekitar 200 bangkai kapal terendam — tujuan penyelaman sejarah terbaik di Karibia.", "Harrison Cave memiliki stalaktit dan stalagmit spektakuler dalam jaringan gua terbesar di Karibia."]},
"BE": {"keuntungan_geografis": ["Belgia di persimpangan Eropa Barat — berbatasan Belanda, Jerman, Luksemburg, Prancis — menjadikan Brussels ibu kota EU dan NATO.", "Pelabuhan Antwerp pelabuhan kedua terbesar di Eropa dan pusat perdagangan berlian terbesar di dunia.", "Tanah datar subur di Flanders mendukung pertanian intensif — pengekspor produk pertanian per kapita tertinggi di EU."], "kerugian_geografis": ["Wilayah sangat kecil (30.528 km persegi) dan padat (376 orang/km persegi) — seluruh negara lebih kecil dari Jawa Barat.", "Tidak memiliki fitur geografis pertahanan alami — wilayah datar menyebabkan Belgia menjadi medan invasi berulang dalam sejarah."] , "fakta_unik": ["Belgia punya tiga wilayah geografis berbeda — Dataran Pesisir, Dataran Tengah, dan Dataran Tinggi Ardennes.", "Sungai Meuse dan Scheldt membelah Belgia — jalan tol air Eropa ke pelabuhan Antwerp dan Rotterdam.", "Tripoin Belgia-Belanda-Jerman di dekat Aachen menjadi salah satu yang paling terkenal di Eropa."]},
"BF": {"keuntungan_geografis": ["Burkina Faso di tengah Afrika Barat, berbatasan 6 negara — titik transit perdagangan regional Sahel.", "Dataran tinggi Mossi (300-400 m) menyediakan lahan relatif datar untuk pertanian jagung, milet, dan sorghum.", "Sungai Mouhoun (Volta Merah) mengalir ke Danau Volta Ghana — potensi irigasi dan energi hidro."], "kerugian_geografis": ["Negara terkurung darat di Sahel — salah satu paling jauh dari laut, tidak punya pantai sama sekali.", "Gurun Sahara menggusur wilayah subur ke selatan (desertifikasi) — mengancam pertanian 80% penduduk."], "fakta_unik": ["Tebing Sindou formasi batu pasir merah setinggi 100 m — sering disebut Grand Canyon Afrika Barat.", "Sungai Mouhoun satu-satunya sungai permanen — lainnya hanya mengalir musiman (Juni-September).", "Pohon baobab berusia 1.500+ tahun di dekat Ouahigouya — salah satu tertua di Afrika Barat."]},
"BH": {"keuntungan_geografis": ["Bahrain kepulauan 33 pulau di tengah Teluk Persia — posisi strategis antara Arab Saudi dan Qatar.", "Teluk Bahrain dangkal dan hangat, habitat terumbu karang terbaik di Teluk Persia dengan 300+ spesies ikan.", "Jembatan King Fahd (25 km) menghubungkan Bahrain ke Arab Saudi — satu-satunya jembatan lintas negara di Teluk Persia."], "kerugian_geografis": ["Pulau sangat kecil (780 km persegi) dengan sumber air tawar terbatas — sebagian besar air dari desalinasi.", "Wilayah datar (titik tertinggi 134 m) dan sebagian besar lahan direklamasi dari laut, rentan kenaikan laut."], "fakta_unik": ["Pohon Kehidupan (Tree of Life) Bahrain — mesquite 400+ tahun tumbuh di tengah gurun tanpa sumber air terlihat.", "Nama Bahrain dari bahasa Arab meaning dua laut — mata air tawar di bawah laut asin dimanfaatkan 5.000 tahun.", "Bahrain negara pertama di Teluk Persia yang menemukan minyak (1932) — sekarang beralih ke keuangan Islam."]},
"BI": {"keuntungan_geografis": ["Burundi di cekungan Danau Tanganyika — danau terdalam ke-2 dunia (1.470 m), menyediakan ikan dan jalur air ke Tanzania.", "Iklim tropis dataran tinggi (1.400-1.800 m) di pegunungan Kongo-Nil ideal untuk kopi dan teh berkualitas.", "Sumber mata air di puncak pegunungan mengalir ke dua cekungan sungai terbesar Afrika — Kongo dan Nil."], "kerugian_geografis": ["Terkurung darat dan terpadat di Afrika (463 orang/km persegi) — tekanan lahan menyebabkan erosi parah.", "Topografi berbukit curam menyebabkan erosi masif — lahan pertanian berkurang akibat longsor."] , "fakta_unik": ["Burundi berbagi Danau Tanganyika sebagai perbatasan alami dengan Tanzania dan Kongo.", "Sumber Sungai Ruvubu di utara adalah salah satu mata air Sungai Nil.", "Dataran tinggi rata-rata 1.700 m — disebut Negara Seribu Bukit bersama Rwanda."]},
"BL": {"keuntungan_geografis": ["Saint Barthelemy di Lesser Antilles dengan pantai pasir putih dan perairan biru jernih — destinasi wisata mewah.", "Pulau vulkanik dengan teluk terlindung Gustavia Harbor — pelabuhan alami untuk yacht dan kapal pesiar.", "Terumbu karang habitat 180+ spesies ikan dan 40+ spesies karang — surga snorkeling dan diving."], "kerugian_geografis": ["Pulau sangat kecil (21 km persegi) — bergantung penuh pada penampungan air hujan dan impor.", "Hurricane Irma 2017 menghancurkan sebagian besar bangunan di pulau ini."], "fakta_unik": ["Saint Barthelemy satu-satunya wilayah Karibia berbudaya Swedia — dikuasai Swedia 1784-1878.", "Pantai Shell Beach ditutupi jutaan kerang — pantai pasir kerang yang unik di dunia.", "Gustavia dinamai dari Raja Gustav III Swedia — fortifikasi Swedia masih terlihat."]},
"BN": {"keuntungan_geografis": ["Brunei di pantai utara Kalimantan menghadap Laut Cina Selatan — posisi strategis jalur perdagangan Asia Tenggara.", "Hutan hujan tropis menutupi 72% wilayah — tutupan hutan tertinggi di Asia Tenggara.", "Cadangan minyak dan gas lepas pantai sangat besar — sekitar 300.000 barrel minyak per hari."], "kerugian_geografis": ["Negara kecil (5.765 km persegi) terkurung dalam Malaysia (Sarawak) — dikelilingi satu negara.", "Penduduk tinggal di pesisir dataran rendah — rentan kenaikan permukaan laut dan banjir rob."], "fakta_unik": ["Istana Nurul Iman ISTANA TERBESAR di dunia — 1.788 kamar dan 257 kamar mandi.", "Taman Ulu Temburong hutan hujan tertua di Borneo — hanya bisa diakses perahu panjang.", "Kampung Ayer di Bandar Seri Begawan desa terapung terbesar di dunia — 30.000+ penduduk."]},
"BO": {"keuntungan_geografis": ["Danau Titicaca di perbatasan — danau navigasi tertinggi di dunia (3.812 m) batas alami dengan Peru.", "Keberagaman geografis dari Andes bersalju (6.500+ m) hingga hutan Amazon — 6 dari 8 zona iklim dunia.", "Salar de Uyuni dataran garam terbesar di dunia (10.582 km persegi) — 50-70% cadangan litium dunia."], "kerugian_geografis": ["Kehilangan akses laut setelah Perang Pasifik 1879-1883 — negara daratan terkurung setelah Chili merebut pesisir.", "Pegunungan Andes menyebabkan isolasi — perjalanan antar kota bisa berhari-hari saat musim hujan."] , "fakta_unik": ["Salar de Uyuni jadi cermin alami terbesar — lapisan air tipis memantulkan langit dengan sempurna.", "Danau Titicaca danau tertinggi dunia yang bisa dilayari — rumah orang Uros di pulau totora.", "Nevado Sajama (6.542 m) gunung tertinggi Bolivia dengan gletser tropis tertinggi di Andes."]},
"BW": {"keuntungan_geografis": ["Delta Okavango delta pedalaman terbesar di dunia (15.000 km persegi) — sura satwa liar UNESCO.", "Posisi stabil di tengah Afrika Selatan, jauh dari pantai rawan konflik — keamanan geopolitik unik.", "Gurun Kalahari (70% wilayah) mengandung berlian — produsen berlian terbesar berdasarkan nilai di dunia."], "kerugian_geografis": ["Terkurung darat, 70% gurun Kalahari — akses air bersih terbatas di sebagian besar negara.", "Musim kering 8 bulan menyebabkan kekeringan berkala yang mengancam pertanian dan satwa liar."], "fakta_unik": ["Delta Okavango satu-satunya delta besar yang mengalir ke daratan — air dari Angola menghilang di pasir.", "Makgadikgadi Pan gurun garam 12.000 km persegi — habitat migrasi zebra terbesar kedua di Afrika.", "Populasi gajah liar terbesar di dunia (130.000+) di Taman Nasional Chobe."]},
"CF": {"keuntungan_geografis": ["Di jantung benua Afrika, berbatasan 6 negara — posisi sentral perdagangan regional.", "Hutan hujan tropis selatan menyimpan 3.600+ spesies tumbuhan dan 209 spesies mamalia.", "Sungai Ubangi dan Sangha ke Sungai Kongo — sistem sungai terbesar kedua di dunia."], "kerugian_geografis": ["Terkurung darat di tengah Afrika — akses laut memerlukan perjalanan lewat negara tetangga.", "Hanya 700 km jalan beraspal di seluruh negara — infrastruktur transportasi sangat minim."], "fakta_unik": ["Air terjun Boali (50 m tinggi, 250 m lebar) terbesar di Republik Afrika Tengah.", "Dzanga-Sangha salah satu dari sedikit tempat di dunia gorila dataran rendah bisa diamati.", "Kubah granit alami 1.000 m di dataran tinggi Bongo — disebut kubah gajah raksasa."]},
"CI": {"keuntungan_geografis": ["Pantai Gading menghadap Teluk Guinea dengan 515 km garis pantai — pelabuhan Abidjan terbesar Afrika Barat.", "Hutan tropis selatan 25% hutan Afrika Barat — produsen kakao terbesar di dunia (40% supply global).", "Sungai Como, Bandama, dan Cavally menyediakan irigasi untuk perkebunan karet dan kakao."], "kerugian_geografis": ["Perbatasan selatan berupa laguna dan rawa — banjir musiman mengancam Abidjan dan San Pedro.", "Deforestasi masif 80% hutan hilang sejak 1960 — erosi tanah akibat perluasan perkebunan kakao."], "fakta_unik": ["Parit Assinie saluran air alami 30 km membelah laguna Ebrie — jalur navigasi unik.", "Taman Nasional Tai hutan hujan primer terbesar Afrika Barat — Situs Warisan Dunia UNESCO.", "Basilika Yamoussoukro kubah 158 m — gereja Kristen terbesar di dunia, melampaui St. Peter Vatikan."]},
"CM": {"keuntungan_geografis": ["Garis pantai 402 km di Teluk Guinea — pelabuhan Douala terbesar Afrika Tengah.", "Gunung Kamerun (4.095 m) gunung berapi tertinggi Afrika Barat — dari tropis hingga alpine dalam satu gunung.", "Kamerun disebut Afrika Mini — pantai, hutan hujan, sabana, gunung, dan danau dalam satu negara."], "kerugian_geografis": ["Hutan hujan selatan menyulitkan infrastruktur — jalan sangat mahal dibangun.", "Gunung Kamerun masih AKTIF — letusan terakhir 2000, gas CO2 Danau Nyos 1986 menewaskan 1.700 orang."] , "fakta_unik": ["Danau Nyos meletuskan gas CO2 1986 — fenomena limnic eruption menewaskan 1.746 orang.", "Gunung Kamerun naik langsung dari Samudra Atlantik — satu-satunya gunung berapi aktif Afrika di tepi laut.", "Waza National Park habitat singa, gajah, jerapah — salah satu taman nasional terbaik Afrika Barat."]},
"CU": {"keuntungan_geografis": ["Pulau terbesar Karibia (109.884 km persegi) di mulut Teluk Meksiko — mengontrol jalur laut ke Florida.", "Ladang tembakau Pinar del Rio (Vuelta Abajo) menghasilkan tembakau berkualitas tertinggi — bahan cerutu Cohiba.", "Terumbu karang Kuba terbesar di Karibia — 2.000+ spesies ikan dan 50+ spesies karang."], "kerugian_geografis": ["Di jalur hurricane Karibia — rata-rata 1-2 badai besar per tahun, kerusakan miliaran dolar.", "Blokade ekonomi AS 60+ tahun membatasi akses perdagangan internasional."], "fakta_unik": ["Kuba punya LEBIH BANYAK DOKTER per kapita dari negara mana pun — 8,2 dokter per 1.000 penduduk.", "Zapata Swamp (4.500 km persegi) rawa terbesar Karibia — habitat buaya Kuba endemik.", "Kuba adalah SATU-SATUNYA negara komunis di Karibia dan salah satu dari sedikit di hemisphere barat."]},
"CV": {"keuntungan_geografis": ["Kepulauan Tanjung Verde 570 km lepas pantai Afrika Barat — posisi strategis di tengah Samudra Atlantik.", "Angin dagang konsisten ideal untuk energi angin — 30% listrik dari pembangkit angin.", "Perairan kaya ikan tuna — perikanan 80% ekspor dan tulang punggung ekonomi kepulauan."], "kerugian_geografis": ["Sumber air tawar sangat terbatas — kekeringan berkepanjangan sejak 1960.", "Terpencil di tengah Atlantik — biaya transportasi tinggi, rentan badai tropis."], "fakta_unik": ["Tanjung Verde negara pulau paling kering di Afrika — pulau-pulau selatan hampir gurun.", "Pico do Fogo (2.829 m) gunung berapi AKTIF — letusan 2014 memaksa evakuasi seluruh pulau.", "Awalnya TIDAK BERPENDUDUK — ditemukan Portugis 1456 sebagai basis perdagangan budak Afrika."]},
"ER": {"keuntungan_geografis": ["Garis pantai 2.234 km di Laut Merah — salah satu terpanjang di Afrika, termasuk 350+ pulau.", "Pelabuhan Massawa dan Assab menghadap jalur pelayaran Laut Merah — 12% perdagangan global.", "Dankalia Depression salah satu tempat terpanas di bumi — potensi energi panas bumi (geothermal)."], "kerugian_geografis": ["80% gurun dan semi-gurun — hanya 5% lahan bisa ditanami, ketergantungan impor pangan.", "Ibu kota Asmara di dataran tinggi 2.325 m, terisolasi dari pesisir oleh pegunungan terjal."], "fakta_unik": ["Dankalia Depression titik terendah Afrika di bawah permukaan laut — lebih panas dari Death Valley.", "Kota Massawa di pesisir dan Asmara di dataran tinggi — perbedaan suhu 15 derajat dalam 100 km.", "Eritrea memiliki lebih dari 350 pulau di Laut Merah — banyak belum dijelajahi."]},
"FJ": {"keuntungan_geografis": ["Fiji terletak di tengah Samudra Pasifik Selatan dengan 333 pulau — posisi strategis sebagai hub penerbangan Pasifik.", "Terumbu karang Fiji (4.000 mil persegi) dan laguna paling luas di Pasifik Selatan — surga diving kelas dunia.", "Hutan tropis menutupi 56% Fiji — sumber kayu keras dan keanekaragaman hayati endemik tinggi."], "kerugian_geografis": ["Kepulauan terpencil di Pasifik Selatan — biaya logistik sangat tinggi untuk impor dan ekspor.", "Beberapa pulau aktif secara vulkanik — Taveuni memiliki gunung berapi aktif dan sering gempa bumi."] , "fakta_unik": ["Fiji memiliki 333 pulau tapi hanya 110 yang dihuni — pulau-pulau kecil banyak yang masih alami.", "Taveuni disebut Garden Island — 80% ditutupi hutan hujan primer dengan waterfall Tavoro spektakuler.", "Fiji adalah negara pertama di Pasifik yang menerima pengungsi iklim dari Kiribati dan Tuvalu."]},
"FM": {"keuntungan_geografis": ["Mikronesia terdiri 607 pulau di Pasifik barat — masing-masing negara bagian (Yap, Chuuk, Pohnpei, Kosrae) punya karakter unik.", "Terumbu karang Chuuk Lagoon dengan 50+ bangkai kapal Perang Dunia II — tujuan penyelaman sejarah terbaik di Pasifik.", "Pohnpei memiliki reruntuhan Nan Madol — kota kuno di atas terumbu karang, dikenal sebagai Venice Pasifik."], "kerugian_geografis": ["Negara kepulauan sangat terpencil — 2.900 km dari Hawaii, transportasi dan logistik sangat mahal.", "Garis pantai rendah (rata-rata 2 m) membuat seluruh negara rentan terhadap kenaikan permukaan laut."] , "fakta_unik": ["Nan Madol di Pohnpei kota kuno dari 92 pulau buatan — dikenal sebagai Venice Pasifik, UNESCO World Heritage.", "Chuuk Lagoon punya armada Jepang yang karam — 50+ bangkai kapal menjadi museum bawah laut.", "Pulau Yap terkenal dengan batu rai — uang batu raksasa berdiameter hingga 3,6 m yang diletakkan di jalan."]},
"GD": {"keuntungan_geografis": ["Grenada di Karibia selatan dengan 121 km garis pantai dan pelabuhan alami St. George yang terlindung.", "Gunung St. Catherine (840 m) menyediakan tanah vulkanik subur — Grenada produsen utama pala dunia (nutmeg).", "Terumbu karang sekitar Grenada menjadi habitat penyu dan lumba-lumba — menarik wisata bahari."] , "kerugian_geografis": ["Hurricane Ivan 2004 menghancurkan 90% bangunan di Grenada — negara rentan terhadap badai Karibia.", "Pulau kecil (344 km persegi) dengan ekonomi bergantung pada satu komoditas (pala/nutmeg)."] , "fakta_unik": ["Grenada disebut Spice Isle — produsen pala terbesar kedua di dunia setelah Indonesia.", "Grand Anse Beach 3 km panjang — salah satu pantai terbaik di Karibia dengan pasir putih halus.", "Underwater Sculpture Park Grenada pertama di dunia — patung bawah laut yang menjadi terumbu karang buatan."]},
"GM": {"keuntungan_geografis": ["Gambia mengapung di sepanjang Sungai Gambia (1.120 km) — sungai navigasi yang membelah negara dari timur ke barat.", "Posisi di Afrika Barat menghadap Atlantik dengan 80 km garis pantai — akses langsung jalur perdagangan maritim.", "Tanah aluvial di sepanjang sungai subur untuk pertanian — kacang tanah (groundnut) menjadi komoditas ekspor utama."] , "kerugian_geografis": ["Gambia adalah negara TERKECIL di daratan Afrika (10.689 km persegi) — dikelilingi Senegal kecuali pesisir.", "Sungai Gambia banjir saat musim hujan — daerah rendah sepanjang sungai terendam berkala."] , "fakta_unik": ["Gambia NEGARA TERKECIL di daratan Afrika — bentuknya panjang dan sempit mengikuti aliran Sungai Gambia.", "James Island di Sungai Gambia Situs Warisan Dunia — bekas benteng perdagangan budak ke Amerika.", "Kiang West National Park habitat hipopotamus, hyena, dan 250+ spesies burung di tepi Sungai Gambia."]},
"GW": {"keuntungan_geografis": ["Guinea-Bissau di pesisir Afrika Barat dengan 350 km garis pantai dan Kepulauan Bissagos (88 pulau) yang kaya biodiversitas.", "Hutan mangrove terbesar di Afrika Barat menutupi pesisir — habitat kura-kura, buaya, dan ikan tropis.", "Arsipelago Bissagos dengan masyarakat matriarchal — budaya Bijagos unik di dunia dan ekosistem terjaga."] , "kerugian_geografis": ["Iklim muson dengan musim hujan sangat basah (Juni-Oktober) — banjir parah menghambat transportasi dan pertanian.", "Infrastruktur sangat minim — salah satu negara paling underdeveloped di Afrika Barat."] , "fakta_unik": ["Kepulauan Bissagos (88 pulau) salah satu dari sedikit tempat di dunia dengan masyarakat matriarchal.", "Guinea-Bissau memiliki hutan mangrove terbesar Afrika Barat — penting untuk penyerapan karbon global.", "Sungai Geba dan Corubal membentuk delta luas — ideal untuk pertanian padi dan perikanan tradisional."]},
"HM": {"keuntungan_geografis": ["Pulau Heard dan McDonald terletak di Samudra Hindia selatan — salah satu tempat paling terisolasi di bumi.", "Gunung Mawson (2.745 m) gunung berapi aktif — ekosistem sub-Antartika yang hampir tidak tersentuh manusia.", "Perairan kaya akan krill dan plankton — mendukung populasi anjing laut, gajah laut, dan penguin."] , "kerugian_geografis": ["80% permukaan tertutup gletser — tidak ada penduduk permanen, hanya stasiun penelitian.", "Lokasi sangat terpencil (4.000 km dari Australia) — akses hanya memungkinkan dengan kapal beberapa bulan setahun."] , "fakta_unik": ["Pulau Heard memiliki SATU-SATUNYA gunung berapi aktif di wilayah Australia — Big Ben meletus berkali-kali.", "Seluruh wilayah adalah Situs Warisan Dunia UNESCO — salah satu dari sedikit tempat di bumi tanpa spesies invasif.", "Perairan sekitar pulau Marine Reserve terbesar di Australia — rumah bagi 43 spesies burung laut."]},
"IO": {"keuntungan_geografis": ["Teritorial Samudra Hindia Britania mencakup Kepulauan Chagos — atol Diego Garcia menjadi pangkalan militer AS-UK strategis.", "Perairan sekitar atol kaya terumbu karang — ekosistem laut yang hampir tidak tersentuh manusia.", "Posisi di tengah Samudra Hindia menguasai jalur pelayaran antara Timur Tengah dan Asia Pasifik."], "kerugian_geografis": ["Atol dataran rendah (rata-rata 1-2 m) sangat rentan terhadap kenaikan permukaan laut.", "Populasi Chagossian diusir 1967-1973 untuk pangkalan militer — isu hak asasi manusia yang belum terselesaikan."], "fakta_unik": ["Atol Diego Garcia salah satu atol terbesar di dunia — lagunanya lebih besar dari seluruh Washington DC.", "Perairan Chagos memiliki 220+ spesies karang dan 1.000+ spesies ikan — biodiversitas laut tertinggi di Samudra Hindia.", "Chagos Archipelago dinyatakan Marine Protected Area terbesar di dunia (640.000 km persegi) pada 2010."]},
"JM": {"keuntungan_geografis": ["Jamaika di Karibia utara dengan 1.022 km garis pantai — pantai Negril dan Montego Bay menjadi destinasi wisata terkenal.", "Blue Mountains (2.256 m) menghasilkan kopi Blue Mountain — salah satu kopi termahal di dunia ($50+/kg).", "Posisi dekat Kuba dan Hispaniola membuat Jamaica transit point penting di Karibia."], "kerugian_geografis": ["Karst limestone di barat menyebabkan longsor dan erosi parah — bencana alam sering terjadi saat hujan deras.", "Pulau berada di zona gempa dan jalur hurricane — gempa 1692 menghancurkan Port Royal ke dasar laut."], "fakta_unik": ["Blue Mountain Peak (2.256 m) dari puncaknya bisa melihat KUBA saat cuaca cerah — 145 km di seberang laut.", "Lagoon Blue Hole di Ocho Rios lubang gua alami di laut — salah satu spot diving paling terkenal di Karibia.", "Port Royal disapu ke dasar laut oleh gempa 1692 — kini Situs Warisan Dunia bawah laut."]},
"JO": {"keuntungan_geografis": ["Yordania menguasai sebagian Laut Mati — titik terendah di daratan bumi (minus 430 m) yang kaya mineral potas.", 